# Generated by Django 4.2.2 on 2023-06-13 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('fullname', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('proposal_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('denied', 'denied'), ('approved', 'approved')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Credit Proposals',
            },
        ),
    ]
