# Generated by Django 4.2.2 on 2023-06-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditproposal",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Credit Proposals",
            },
        ),
    ]
