# Generated by Django 4.2.2 on 2023-06-15 11:45

import uuid

import django.db.models.deletion

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_creditproposal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("denied", "denied"),
                            ("approved", "approved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status da Proposta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProposalFields",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "field_name",
                    models.CharField(max_length=60, verbose_name="Nome do Campo"),
                ),
                (
                    "field_title",
                    models.CharField(max_length=60, verbose_name="Título do Campo"),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("text", "text"), ("number", "number")],
                        max_length=20,
                        verbose_name="Tipo do Campo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proposal Fields",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="creditproposal",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Old Credit Proposals",
            },
        ),
        migrations.CreateModel(
            name="ProposalFieldsValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "field_value",
                    models.CharField(max_length=60, verbose_name="Valor do Campo"),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal_field",
                        to="api.proposalfields",
                        verbose_name="Campo",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposal",
                        to="api.proposal",
                        verbose_name="Nº da Proposta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proposal Fields Values",
                "ordering": ["-created_at"],
            },
        ),
    ]
