# Generated by Django 4.2.2 on 2023-06-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_proposal_proposalfields_alter_creditproposal_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proposalfields",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Proposal Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="proposalfieldsvalue",
            options={
                "ordering": ["created_at"],
                "verbose_name_plural": "Proposal Fields Values",
            },
        ),
    ]
